version: '3.7'

services:
  nest-semi-hexagon-db:
    image: 985465380175.dkr.ecr.ap-southeast-1.amazonaws.com/postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - nest-semi-hexagon-db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 20s
      retries: 10
    networks:
      - nest-semi-hexagon-network

  nest-semi-hexagon-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    depends_on:
      nest-semi-hexagon-db:
        condition: service_healthy
    volumes:
      - .:/www/app
      - /www/app/node_modules
    command: /bin/sh -c "npm run migrate && npm run start:dev"
    networks:
      - nest-semi-hexagon-network

networks:
  nest-semi-hexagon-network:

volumes:
  nest-semi-hexagon-db:
