version: '3.7'

services:
  eigen-db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - eigen-db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 20s
      retries: 10
    networks:
      - eigen-network

  eigen-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    depends_on:
      eigen-db:
        condition: service_healthy
    volumes:
      - .:/www/app
      - /www/app/node_modules
    command: /bin/sh -c "npm run migrate && npm run start:dev"
    networks:
      - eigen-network

networks:
  eigen-network:

volumes:
  eigen-db:
